### ISSUE TITLE
Issue sending custom fields

### ISSUE THREAD

**Issue by alexandrefc1** [huksley/gelf-logger#4]
Hi,

I found a issue when getting custom fields: 

It can be solved changing this code in class GelfHandler:
`if (f != null) {
            for (StringTokenizer en = new StringTokenizer(f, ",; \r\n\t"); en.hasMoreElements();) {
                String v = en.nextToken();
                if (v != null && !v.trim().equals("=")) {
                    String n = v;
                    int eqi = v.indexOf("=");
                    if (eqi >= 0) {
                        v = v.substring(eqi + 1);
                        n = n.substring(0, eqi);
                        getFields().put(n, v);
                    }
                }
            }
        }`

with this:

`if (f != null) {
            for (StringTokenizer en = new StringTokenizer(f, ",; \r\n\t"); en.hasMoreElements();) {
                String v = en.nextToken();
                if (v != null && v.trim().equals("=")) {
                    String n = v;
                    int eqi = v.indexOf("=");
                    if (eqi >= 0) {
                        v = v.substring(eqi + 1);
                        n = v.substring(0, eqi);
                        getFields().put(n, v);
                    }
                }
            }
        }`

**Comment by huksley** [comment]
Hi!
As far as I see, you have misplaced two code pieces - it actually must be reversed?

**Comment by huksley** [comment]
I`ve fixed it, please verify. If ok, close please.

**Comment by alexandrefc1** [comment]
Hi,
Hi!

I made a mistake in the solution I put in the first comment.

The changes you've done are ok, but one more is needed:
Now you have this, but that's wrong:
v = v.substring(eqi + 1);
n = v.substring(0, eqi);

The correct way is:
v = v.substring(eqi + 1);
n = n.substring(0, eqi);

Sorry for the mistake.

**Comment by huksley** [comment]
Thanks for the tip. Modified it.
